apiVersion: v1
kind: Service
metadata:
  labels:
    service: model-server
  name: model-server
  namespace: backend
spec:
  ports:
  - name: "18811"
    port: 18811
    targetPort: 18811
  selector:
    service: model-server